#!/bin/bash

# Huge history. Doesn't appear to slow things down, so why not?
export HISTSIZE=50000
export HISTFILESIZE=100000

# Avoid duplicate entries
export HISTCONTROL="ignoredups"

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT='%F %T '

# Lazy load NVM to speed up shell start time.
# https://gist.github.com/fl0w/07ce79bd44788f647deab307c94d6922
lazynvm() {
  unset -f nvm node npm
  export NVM_DIR="$HOME/.nvm"
  # shellcheck disable=SC1090
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  # shellcheck disable=SC1090
  [ -r "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
}

nvm() {
  lazynvm
  nvm "$@"
}

node() {
  lazynvm
  node "$@"
}

npm() {
  lazynvm
  npm "$@"
}

if [ -d "$HOME/.rbenv" ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

if [ -d "$HOME/.bats" ]; then
  export PATH="$HOME/.bats/bin:$PATH"
fi

if [ -d "$HOME/.bin" ]; then
  export PATH="$HOME/.bin:$PATH"
fi

# Custom bash prompt
export PS1="\[\e[0;36m\]\W:\[\e[0;33m\]\$(__git_ps1)\[\e[0m\] "
