#!/bin/bash

# Lazy load NVM to speed up shell start time.
# https://gist.github.com/fl0w/07ce79bd44788f647deab307c94d6922
lazynvm() {
  unset -f nvm node npm
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . $NVM_DIR/nvm.sh
  [ -r "$NVM_DIR/bash_completion" ] && . $NVM_DIR/bash_completion
}

nvm() {
  lazynvm
  nvm $@
}

node() {
  lazynvm
  node $@
}

npm() {
  lazynvm
  npm $@
}

if [ -d $HOME/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

if [ -d $HOME/.bats ]; then
  export PATH="$HOME/.bats/bin:$PATH"
fi

if [ -d $HOME/.bin ]; then
  export PATH="$HOME/.bin:$PATH"
fi

# Custom bash prompt
export PS1="\[$(tput setaf 6)\]\W:\[$(tput setaf 3)\]\$(__git_ps1) \[$(tput sgr0)\]"
