#!/usr/bin/ruby

require 'irb'
require 'irb/completion'
require 'rubygems'

IRB.conf[:AUTO_INDENT] = true # Ruby 2.7: true is new default https://bit.ly/2IYxNqc
IRB.conf[:USE_READLINE] = true
IRB.conf[:PROMPT_MODE] = :SIMPLE # Use `>>` for prompt.
IRB.conf[:SAVE_HISTORY] = 1000

def local_methods(obj=self)
  (obj.public_methods - Object.public_methods - Object.instance_methods).sort
end

def predicates(obj=self)
  local_methods(obj).grep(/\?$/)
end

def locate(obj, method)
  obj.method(method.to_sym).source_location
end

def time(iterations: 1)
  require 'benchmark'
  Benchmark.measure { iterations.times { yield } } if block_given?
end

def copy
  system "echo \"#{IRB.CurrentContext.last_value}\" | pbcopy"
  true
end

def q
  exit
end

def clear
  system 'clear'
  "Ruby #{RUBY_VERSION}p#{RUBY_PATCHLEVEL}"
end

railsrc = File.expand_path('~/.railsrc')
load railsrc if File.exist?(railsrc) && (ENV['RAILS_ENV'] || defined? Rails)

puts "Ruby #{RUBY_VERSION}p#{RUBY_PATCHLEVEL}"
