#!/bin/bash

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

brew_prefix="$(brew --prefix)"

# Load bash completion
if [ -f "$brew_prefix/etc/bash_completion" ]; then
  # shellcheck disable=SC1091
  . "$brew_prefix/etc/bash_completion"

  # Set autocomplete for "g" git alias
  __git_complete g __git_main
fi

# Load grc (Terminal colorizer)
if [ -f "$brew_prefix/etc/grc.bashrc" ]; then
  # shellcheck disable=SC1091
  . "$brew_prefix/etc/grc.bashrc"
fi

for profile_config in "$HOME"/.profile.d/*.sh
do
  # shellcheck disable=SC1090
  source "$profile_config"
done

unset brew_prefix profile_config

if [ ! -f "$HOME/.bash_local" ]; then
  touch "$HOME/.bash_local"
fi
# shellcheck disable=SC1091
source "$HOME/.bash_local"

# Bash Prompt
# folder_name: (git_branch_name)
export PS1="\[\e[0;36m\]\W:\[\e[0;33m\]\$(__git_ps1)\[\e[0m\] "

# Bash History
export HISTFILESIZE="${HISTSIZE}";
export HISTFILE="$HOME/.bash_history"
export HISTCONTROL="ignoredups"
# Use standard ISO 8601 timestamp.
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT='%F %T '

alias h='history'
