#!/usr/bin/env bash

set -e

if [ -z "$CLOUD66_DIR" ]; then
  CLOUD66_DIR="$HOME/Projects/dotfiles/bin"
fi

echo -e "\nInstalling latest Cloud 66 toolbelt..."

curl https://app.cloud66.com/toolbelt/osx -L -o cloud66.zip

unzip cloud66.zip

cp cx_*_darwin_amd64/cx "$CLOUD66_DIR"

rm -rf cloud66.zip cx_*_darwin_amd64
