#!/usr/bin/env bash

set -e

if [ -z "$CODA_DIR" ]; then
  CODA_DIR="$HOME/Library/Application Support/Coda 2/Modes"
fi

rm -rf $CODA_DIR/Bash.mode $CODA_DIR/CoffeeScript.mode

echo -e "\nInstalling Coda 2 Syntax Modes..."

git clone https://github.com/wwjamieson3/Coda2-bash-mode.git "$CODA_DIR/Bash.mode"
mv $CODA_DIR/Bash.mode/bash.mode/* $CODA_DIR/Bash.mode/

git clone https://github.com/caseywebdev/CoffeeScript.mode.git "$CODA_DIR/CoffeeScript.mode"
