#!/bin/bash

DOTFILES_PATH="$HOME/Projects/dotfiles"
LAPTOP_PATH="$HOME/Projects/laptop"

if [ -d "$DOTFILES_PATH" ]; then
  echo "My dotfiles already installed."
else
  echo "Installing my dotfiles..."
  git clone https://github.com/javierjulio/dotfiles.git "$DOTFILES_PATH"
  cd "$DOTFILES_PATH"
  rake install
fi

shopt -s expand_aliases
source $HOME/.profile
reload

if type brew &>/dev/null; then
  echo -e "\nUpdating Homebrew formula..."
  brew update
else
  echo -e "\nInstalling Homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install git git-lfs bash-completion grc pkgconfig ghostscript imagemagick
brew install openssl
brew install libyaml # should come after openssl
brew install postgresql postgis redis

# Git LFS is a command line extension and specification for managing large files with Git.
git lfs install --force

cd "$LAPTOP_PATH"

./cloud66
./projects
./ruby
./node
./bats

echo -e "\nDone."
