#!/bin/bash

set_base_path() {
  SOURCE="${BASH_SOURCE[0]}"
  DIR="$( dirname "$SOURCE" )"
  while [ -h "$SOURCE" ]
  do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/$SOURCE"
    DIR="$( cd -P "$(dirname "$SOURCE")" && pwd )"
  done
  # shellcheck disable=SC2034
  BASE_PATH="$(cd "$DIR" && pwd)"
}

set_base_path

. link_dotfiles

command_exists () {
  type -P "$1" &> /dev/null ;
}

if command_exists brew ; then
  echo -e "\nUpdating Homebrew..."
  brew update
else
  echo -e "\nInstalling Homebrew..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew bundle --no-upgrade
brew bundle --file=Caskfile

./projects
./ruby
./node
./bats

terminal_theme=$(defaults read ~/Library/Preferences/com.apple.Terminal.plist "Default Window Settings" 2>/dev/null)

if [ "$terminal_theme" != "terminal-ocean-dark" ]; then
  echo -e "\nInstall Terminal theme."
  echo -e "Location: laptop/themes/terminal-ocean-dark.terminal"
fi

unset terminal_theme

echo -e "\nDone."
