#!/usr/bin/env bash

echo "Installing my dotfiles ..."

git clone https://github.com/javierjulio/dotfiles.git ~/Projects/dotfiles
cd ~/Projects/dotfiles
rake install
reload
home

echo "Installing Homebrew ..."
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  brew update

brew install git
brew install bash-completion
brew install grc # http://wynnnetherland.com/journal/a-stylesheet-author-s-guide-to-terminal-colors
brew install gawk # used for matching for colorizing (e.g. match-todos)

echo "Installing PostgreSQL ..."
brew install postgresql

echo "Installing ImageMagick ..."
brew install pkgconfig
brew install imagemagick

# Fix paths so rmagick gem will install successfully (https://coderwall.com/p/wnomjg)
if [ -d /usr/local/Cellar/imagemagick/6.8.0-10/lib ]; then
  echo "Fixing imagemagick 6.8.0-10 lib symlinks so rmagick gem will install successfully."
  cd /usr/local/Cellar/imagemagick/6.8.0-10/lib
  ln -s libMagick++-Q16.7.dylib libMagick++.dylib
  ln -s libMagickCore-Q16.7.dylib libMagickCore.dylib
  ln -s libMagickWand-Q16.7.dylib libMagickWand.dylib
fi

source ./projects

source ./ruby

source ./node

source ./coda
