#!/bin/sh

. ./helpers.sh

log_echo "Symlinking dotfiles..."

(
  cd dotfiles || exit

  for dotfile in *
  do
    ln -nsf "${PWD}/${dotfile}" "${HOME}/.${dotfile}"
  done
)

log_pass "Dotfiles symlinked."
