#!/usr/bin/env bash

shopt -s expand_aliases
source ~/.bashrc
reload

if [ -d ~/.nvm ]; then
  echo -e "\nUpdating nvm..."
  cd ~/.nvm
  git pull
  reload
  echo -e "\nUsing Node.js" `nvm current` "..."
else
  echo -e "\nInstalling nvm..."
  git clone https://github.com/creationix/nvm.git ~/.nvm
  reload

  nvm install 0.10
  nvm alias default 0.10

  echo -e "\nInstalling common npm packages..."
  npm install -g gulp grunt-cli bower coffee-script stylus ember-cli
fi
