#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$HOME/.profile"

NVM_PREFIX="$HOME/.nvm"

if [ -d "$NVM_PREFIX" ]; then
  echo -e "\nUpdating nvm..."
  cd "$NVM_PREFIX" || exit
  git pull
  reload
  echo -e "\nUsing Node.js $(nvm current) ..."
else
  echo -e "\nInstalling nvm..."
  git clone https://github.com/creationix/nvm.git "$NVM_PREFIX"
  reload

  nvm install 10.7.0
  nvm alias default 10.7.0

  echo -e "\nInstalling latest npm..."
  npm install -g npm

  echo -e "\nInstalling common npm packages..."
  npm install -g gulp-cli ember-cli
fi
