#!/usr/bin/env bash

# Try n for Node version management instead of installing by source
# https://github.com/visionmedia/n

echo "Installing Node.js ..."
  git clone https://github.com/joyent/node.git ~/.node
  cd ~/.node
  git checkout v0.10.28
  # may need to specify CC and CXX (clang) from Xcode 4.5 here
  # https://github.com/joyent/node/wiki/Installation
  ./configure --prefix=~/.node
  make
  make install
  reload

echo "Installing common npm packages ..."
  npm install -g gulp grunt-cli bower coffee-script stylus ember-cli
