#!/usr/bin/env bash

echo -e "\nCloning GitHub projects..."

PROJECTS_PREFIX="$HOME/Projects"

projects=( javierjulio.github.io website paysafe activeadmin )

for project in "${projects[@]}"; do
  if [ ! -d "$PROJECTS_PREFIX/$project" ]; then
    git clone "https://github.com/javierjulio/$project.git" "$PROJECTS_PREFIX/$project"
    echo "Cloned $project successfully."
  fi
done

pushd "$PROJECTS_PREFIX/website" >&-
  heroku git:remote --app javierjulio
popd >&-
