#!/usr/bin/env bash

echo -e "\nCloning GitHub projects..."

projects=( website textarea-autosize browser-bug-reports exercism node-hello-world sinatra-blog )

for project in "${projects[@]}"; do
  git clone "https://github.com/javierjulio/$project.git" "$HOME/Projects/$project" &>/dev/null
  if [ $? -ne 0 ]; then
    echo "$project already exists."
  else
    echo "Cloned $project successfully."
  fi
done

if [ -f $HOME/.ssh/heroku-javierjulio_rsa ]; then
  echo -e "\nHeroku SSH key already exists locally."
else
  echo -e "\nSetup SSH key with retrieved Heroku passphrase ...\n"
  
  ssh-keygen -t rsa -C "jjfutbol@gmail.com" -f "/Users/javierjulio/.ssh/heroku-javierjulio_rsa"
  
  echo -e "\nAdd SSH key locally so Heroku CLI functions ...\n"
  
  ssh-add -K ~/.ssh/heroku-javierjulio_rsa
  
  heroku login
  heroku keys:add
fi
