#!/usr/bin/env bash

echo -e "\nCloning GitHub projects..."

PROJECTS_PREFIX="$HOME/Projects"

projects=( website textarea-autosize browser-bug-reports exercism node-hello-world sinatra-blog )

for project in "${projects[@]}"; do
  git clone "https://github.com/javierjulio/$project.git" "$PROJECTS_PREFIX/$project" &>/dev/null
  if [ $? -ne 0 ]; then
    echo "$project already exists."
  else
    echo "Cloned $project successfully."
  fi

  # HTTP GIT now default for Heroku (no SSH auth needed as before)
  # https://blog.heroku.com/archives/2014/12/5/http_git_now_generally_available

  if [ "$project" == "website" ]; then
    ( cd "$PROJECTS_PREFIX/$project" ; heroku git:remote )
  fi

done
