#!/usr/bin/env bash

shopt -s expand_aliases
source $HOME/.bashrc
reload

PYENV_PREFIX="$HOME/.pyenv"

if [ -d $PYENV_PREFIX ]; then
  echo -e "\nUpdating pyenv..."
  cd $PYENV_PREFIX
  git pull
else
  echo -e "\nInstalling pyenv..."
  git clone https://github.com/yyuu/pyenv.git $PYENV_PREFIX
  # no need to export paths as those are in my dotfiles
  reload

  # echo -e "\nInstalling Python 3.5.2..."
  # pyenv install 3.5.2
  # pyenv rehash
  # pyenv global 3.5.2
  # # chown -R $HOME/.pyenv

  # echo -e "\nUpdating PIP and default eggs for Python" `pyenv global` "..."
  # pip install --upgrade pip
  # pip install plumbum
  # pyenv rehash
fi
