#!/usr/bin/env bash

echo "Installing pyenv for managing Python versions ..."
  git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  # no need to export paths as those are in my dotfiles
  exec $SHELL -l

echo "Installing Python 3.4.1 ..."
  pyenv install 3.4.1
  pyenv rehash
  pyenv global 3.4.1
  # chown -R ~/.pyenv

echo "Updating PIP and default eggs for Python" `pyenv global` "..."
  pip install --upgrade pip
  pip install plumbum
  pyenv rehash
