#!/bin/sh

# Run `code` to open Visual Studio Code from the Terminal.
# https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
  export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
fi

alias s="start_dev_server"

start_dev_server() {
  if [ -f ./Procfile.dev ]; then
    echo "Running: foreman start -f Procfile.dev"
    rm log/*.log && foreman start -f Procfile.dev
  elif [ -f ./Procfile ]; then
    echo "Running: foreman start"
    rm log/*.log && foreman start
  elif [ -f ./package.json ]; then
    echo "Running: npm start"
    npm start
  else
    echo "\033[1;31m** No app server found. **\033[0m"
    echo "Looking for a Procfile(.dev) or package.json file."
  fi
}
