#!/bin/sh

# For pipx installed packages
if [ -d "$HOME/.local/bin" ]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.docker/bin" ]; then
  export PATH="$HOME/.docker/bin:$PATH"
fi

# Run `code` to open Visual Studio Code from the Terminal.
# https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
  export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
fi

export EDITOR="code --wait"

alias s="start-development"
