#!/bin/sh

source_google_cloud_sdk_file() {
  if [ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/$1" ]; then
    # shellcheck disable=SC1090
    . "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/$1"
  fi
}

source_google_cloud_sdk_file "path.zsh.inc"
source_google_cloud_sdk_file "completion.zsh.inc"

unset -f source_google_cloud_sdk_file
