#!/bin/sh

source_file() {
  if [ -f "/opt/homebrew/share/google-cloud-sdk/$1" ]; then
    # shellcheck disable=SC1090
    . "/opt/homebrew/share/google-cloud-sdk/$1"
  fi
}

[ -n "$ZSH_VERSION" ] && source_file "path.zsh.inc"
[ -n "$BASH" ] && source_file "path.bash.inc"

unset -f source_file
