#!/bin/bash -e

source_google_cloud_sdk_file() {
  local filename=$1
  local path="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk"
  if [ -f "$path/$filename" ]; then
    # shellcheck disable=SC1090
    source "$path/$filename"
  fi
}

# Updates PATH for the Google Cloud SDK.
source_google_cloud_sdk_file "path.bash.inc"

# Enables shell command completion for gcloud.
source_google_cloud_sdk_file "completion.bash.inc"

unset -f source_google_cloud_sdk_file
