#!/bin/sh

if [ -n "$ZSH_VERSION" ]; then
  autoload -U colors
  colors

  setopt PROMPT_SUBST

  # The output format is:
  #   Desktop:
  #   laptop: (master)
  # shellcheck disable=SC2154
  export PROMPT='%{$fg[cyan]%}%1~:%{$fg[yellow]%}$(__git_ps1  " (%s)")%{$reset_color%} '
elif [ -n "$BASH" ]; then
  # folder_name: (git_branch_name)
  export PS1="\[\e[0;36m\]\W:\[\e[0;33m\]\$(__git_ps1)\[\e[0m\] "
fi
