#!/bin/zsh

autoload -U colors
colors

setopt PROMPT_SUBST

# The output format is:
#   Desktop:
#   laptop: (master)
# shellcheck disable=SC2154
export PS1='%{$fg[cyan]%}%1~: %{$fg[yellow]%}$(__git_ps1 "(%s) ")%{$reset_color%}'
export RPROMPT="%*"
