#!/bin/sh

alias opendir='open -R .'

alias ..='cd ..'
alias home='cd ~'
alias docs='cd ~/Documents'
alias documents='cd ~/Documents'
alias p='cd ~/Projects'
alias projects='cd ~/Projects'
alias laptop='cd ~/Projects/laptop'
alias dotfiles='cd ~/Projects/laptop/dotfiles'
alias jj='cd ~/Projects/javierjulio'

alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

alias r='reload'
alias c='clear'
alias q='exit'

reload() {
  # shellcheck disable=SC1090
  if [ -n "$ZSH_VERSION" ]; then
    . "$HOME/.zshrc"
  elif [ -n "$BASH" ]; then
    . "$HOME/.profile"
  fi
}

executable() {
  chmod +x "$@"
}

search() {
  searchin . "$@"
}

searchin () {
  find "$1" -type f -print0 |
    xargs -0 grep -l "$2"
}

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
emptytrash() {
  sudo rm -rfv /Volumes/*/.Trashes
  sudo rm -rfv ~/.Trash
  sudo rm -rfv /private/var/log/asl/*.asl
}
