name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup bats-core
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - name: Install Shellcheck
        run: brew install shellcheck
      - name: Bats version
        run: bats -v
      - name: Run tests
        run: bats -r test/
