name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BATS_CORE_VERSION: 1.8.2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Check if macos-13 is available https://github.com/actions/runner-images#available-images
        os: [macos-11, macos-12]
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup bats-core
        uses: mig4/setup-bats@v1
        with:
          bats-version: ${{ env.BATS_CORE_VERSION }}
      - name: Install Shellcheck
        run: brew install shellcheck
      - name: Bats version
        run: bats -v
      - name: Run tests
        run: bats -r test/
