name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  BATS_CORE_VERSION: 1.8.2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # For newer versions: https://github.com/actions/runner-images#available-images
        os:
          - macos-13
          - macos-14
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: bats-core/bats-action@2.0.0
        with:
          bats-version: ${{ env.BATS_CORE_VERSION }}
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
      - name: Install Shellcheck
        run: brew install shellcheck
      - name: Bats version
        run: bats -v
      - name: Run tests
        run: bats -r test/
